# Generated by Django 3.2.3 on 2021-07-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('classname', models.CharField(default='', max_length=200)),
                ('grade', models.IntegerField(default='')),
            ],
            options={
                'ordering': ['classname'],
            },
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('att_worship', models.BooleanField(default='')),
                ('att_zoom', models.BooleanField(default='')),
                ('att_date', models.DateField(default='')),
                ('recode_date', models.DateField(default='')),
                ('att_memo', models.CharField(default='',
                                              help_text='Comment contents', max_length=200, blank=True)),
                ('child_id', models.ForeignKey(default='',
                                               on_delete=django.db.models.deletion.CASCADE, to='app.child')),
            ],
        ),
    ]
